#!/bin/sh

. $(dirname $(readlink -f $0))/config.inc.sh

[ -f $DN42_WIKI_RENDERED/hts-in_progress.lock ] && pgrep httrack >/dev/null && exit 0

cd $DN42_WIKI_GIT
OLD_COMMIT=$(git rev-parse --verify HEAD 2>&1)
git pull
NEW_COMMIT=$(git rev-parse --verify HEAD 2>&1)
if [ "$OLD_COMMIT" != "$NEW_COMMIT" ] || [ "$1" = "force" ]; then
    echo "New Changes, updating github repo..."
    git push github master
    echo "Updating rendered repo..."
    cd $DN42_WIKI_RENDERED
    git pull
    #export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
    #RACK_ENV=production gollum --lenient-tag-lookup --css --host $DN42_WIKI_WEB_HOST --port $DN42_WIKI_WEB_PORT --no-edit $DN42_WIKI_GIT 2>/dev/null >/dev/null &
    #GOLLUM_PID=$!
    #until curl -s http://$DN42_WIKI_WEB_HOST:$DN42_WIKI_WEB_PORT >/dev/null; do true; done
    httrack http://$DN42_WIKI_WEB_HOST:$DN42_WIKI_WEB_PORT --update -%F '' -O $DN42_WIKI_RENDERED -*/gollum/history/* -*/gollum/commit/* -*/gollum/latest_changes?* -*/*.md/* >/dev/null
    #kill $GOLLUM_PID
    rsync -aq --delete --exclude '*-[2-9].html' ${DN42_WIKI_WEB_HOST}_${DN42_WIKI_WEB_PORT}/. $DN42_WIKI_GIT/robots.txt $DN42_WIKI_RENDERED/_redirects dist
    find dist/ -type f -print0 | xargs -0 sed -i "s#http://$DN42_WIKI_WEB_HOST:$DN42_WIKI_WEB_PORT/#$DN42_WIKI_HISTORY_URI/#g ; s#<a href=\"../../../../../\">robots.txt</a>#<a href=\"/robots.txt\">robots.txt</a>#g ; s#href=\"\([^\"]\+\)-[2-9].html\"#href=\"\1.html\"#g ; s#anon%40git.dn42_dn42/ca-client.html#anon%40git.dn42:dn42/ca-client# ; s#<a href="whois.html">whois.dn42</a>#<a href="whois.dn42">whois.dn42</a>#g"
    git add .
    git commit -m "update-$(date '+%Y%m%d%H%M%S')"
    git push
fi
